version: 2.1

jobs:

  linux:
    docker:
      - image: cimg/go:1.14
    steps:
      - run:
          name: "Go version"
          command: |
            go version
            go env
      - run:
          name: "Install tools"
          command: |
            curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.23.8
      - checkout
      - run:
          name: "Lint"
          command: golangci-lint run
      - run:
          name: "Test"
          command: go test -v
      - run:
          name: "Benchmark"
          command: go test -run=- -bench=. -benchmem


workflows:
  version: 2
  uint256:
    jobs:
      - linux
