version: 2.1

commands:
  test:
    parameters:
      arch:
        default: "amd64"
        description: The target architecture.
        type: enum
        enum: ["amd64", "386"]
    steps:
      - run:
          name: "Test (<<parameters.arch>>)"
          command: |
            export GOARCH=<<parameters.arch>>
            go version
            go env
            go test -v

jobs:

  linux:
    docker:
      - image: cimg/go:1.14
    steps:
      - run:
          name: "Install tools"
          command: |
            curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.23.8
      - checkout
      - run:
          name: "Lint"
          command: golangci-lint run
      - test:
          arch: "amd64"
      - test:
          arch: "386"
      - run:
          name: "Benchmark"
          command: go test -run=- -bench=. -benchmem


workflows:
  version: 2
  uint256:
    jobs:
      - linux
